name: main
on:
  schedule:
    - cron: 0 */1 * * *
  workflow_dispatch:

jobs:
  twitter:
    name: Upload new Twitter Profile
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm install
      - name: set .env variables
        run: |
          touch .env
          echo "APIKEY=${{ secrets.APIKEY }}" >> .env
          echo "APIKEYSECRET=${{ secrets.APIKEYSECRET }}" >> .env
          echo "ACCESSTOKEN=${{ secrets.ACCESSTOKEN }}" >> .env
          echo "ACCESSTOKENSECRET=${{ secrets.ACCESSTOKENSECRET }}" >> .env
          echo "WEATHERAPIKEY=${{ secrets.WEATHERAPIKEY }}" >> .env
      - name: run
        run: node index.js
